version: 2
build:
  os: ubuntu-20.04  
  image: latest
  apt_packages:
    - cmake

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .